-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })

    if vim.v.shell_error ~= 0 then
        vim.api.nvim_echo({
            { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
            { out,                            "WarningMsg" },
            { "\nPress any key to exit..." },
        }, true, {})
        vim.fn.getchar()
        os.exit(1)
    end
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    spec = {
        { import = "plugins" }
    },
    defaults = {
        lazy = true
    },
    install = { colorscheme = { "habamax" } },
    checker = { enabled = false },
})

-- -- packer
-- local ensure_packer = function()
--     local fn = vim.fn
--     local install_path = fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
--     if fn.empty(fn.glob(install_path)) > 0 then
--         fn.system({ 'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path })
--         vim.cmd [[packadd packer.nvim]]
--         return true
--     end
--     return false
-- end
--
-- local packer_bootstrap = ensure_packer()
--
-- require('packer').startup(function(use)
--     use 'wbthomason/packer.nvim'
--     use 'tpope/vim-fugitive'
--     use 'tpope/vim-rhubarb'
--     --use 'vim-denops/denops.vim'
--
--     -- Color Scheme
--      use {
--          'shaunsingh/nord.nvim', config = function()
--          vim.g.nord_italic = false
--      end, }
--
--     use {
--       'rmehri01/onenord.nvim',
--     }
--
--     use {
--         'neanias/everforest-nvim',
--       config = function()
--           require('everforest').setup({
--               background = 'medium',
--           })
--       end
--     }
--
--     vim.cmd [[colorscheme nord]]
--
--     use {
--         'lukas-reineke/headlines.nvim',
--         after = 'nvim-treesitter',
--         config = function ()
--             require('headlines').setup({
--                 markdown = {
--                     bullets = {},
--                     coldeblock_highlight = 'CodeBlock',
--                     dash_highlight = 'Dash',
--                     quote_highlight = 'Quote',
--                 },
--             })
--         end
--     }
--
--     use 'folke/lsp-colors.nvim'
--
--     -- Project file management
--
--     use {
--         'nvim-neo-tree/neo-tree.nvim',
--         requires = {
--             'nvim-lua/plenary.nvim',
--             'nvim-tree/nvim-web-devicons',
--             'MunifTanjim/nui.nvim'
--         },
--         config = function()
--             require('neo-tree').setup({
--                 filesystem = {
--                     filtered_items = {
--                         always_show = {
--                             ".github",
--                         },
--                     },
--                 },
--             })
--         end,
--     }
--
--     -- Help
--
--     -- Template, Snippet
--     use {
--         'mattn/sonictemplate-vim', setup = function()
--         vim.g.sonictemplate_vim_template_dir = { '~/.templates' }
--         vim.g.sonictemplate_key = 0
--         vim.g.sonictemplate_intelligent_key = 0
--         vim.g.sonictemplate_postfix_key = 0
--     end,
--     }
--
--     use {
--         'nvim-telescope/telescope.nvim',
--         requires = { 'nvim-lua/plenary.nvim' },
--         config = function()
--             require('telescope').setup {
--                 extensions = {
--                     frecency = {
--                         auto_validate = false,
--                     }
--                 }
--             }
--         end,
--     }
--
--     use {
--         "nvim-telescope/telescope-frecency.nvim",
--         config = function()
--             require "telescope".load_extension("frecency")
--         end,
--         requires = { "kkharji/sqlite.lua" }
--     }
--
--     use {
--         "epwalsh/obsidian.nvim",
--         tag = "*",
--         requires = { "nvim-lua/plenary.nvim", "hrsh7th/nvim-cmp" },
--         config = function()
--             require('obsidian').setup({
--                 workspaces = {
--                     {
--                         name = "notes",
--                         path = "~/Documents/Notes/Notes",
--                     }
--                 },
--                 daily_notes = {
--                     folder = "dailynotes",
--                     date_format = "%Y-%m-%d",
--                     template = "2_daily.md",
--                 },
--                 use_advanced_uri = true,
--                 picker = {
--                     name = "telescope.nvim",
--                 },
--                 completion = {
--                     nvim_cmp = true,
--                     min_chars = 2,
--                 },
--                 follow_url_func = function(url)
--                     vim.fn.jobstart({ "xdg-open", url })
--                 end,
--                 note_id_func = function(title)
--                     -- Create note IDs in a Zettelkasten format with a timestamp and a suffix.
--                     -- In this case a note with the title 'My new note' will be given an ID that looks
--                     -- like '1657296016-my-new-note', and therefore the file name '1657296016-my-new-note.md'
--                     local suffix = ""
--                     if title ~= nil then
--                         -- If title is given, transform it into valid file name.
--                         suffix = title:gsub(" ", "-"):gsub("[^A-Za-z0-9-ぁ-んァ-ヶｱ-ﾝﾞﾟ一-龠]", ""):lower()
--                     else
--                         -- If title is nil, just add 4 random uppercase letters to the suffix.
--                         for _ = 1, 4 do
--                             suffix = suffix .. string.char(math.random(65, 90))
--                         end
--                     end
--                     return suffix
--                 end,
--             })
--         end,
--     }
--
--     -- Completion
--     use {
--         'yetone/avante.nvim',
--         branch = 'main',
--         requires = {
--             'stevearc/dressing.nvim',
--             'nvim-lua/plenary.nvim',
--             'MunifTanjim/nui.nvim',
--
--             'nvim-tree/nvim-web-devicons',
--             'HakonHarnes/img-clip.nvim',
--             'zbirenbaum/copilot.lua',
--         },
--         event = 'InsertEnter',
--         config = function ()
--             require('copilot').setup({
--                copilot_node_command = os.getenv('HOME') .. '/.local/share/mise/installs/node/20.8.1/bin/node'
--             })
--             require('avante').setup({
--                 provider = 'copilot'
--             })
--         end
--     }
--     -- use {
--     --     'zbirenbaum/copilot.lua',
--     --     cmd = 'Copilot',
--     --     event = 'InsertEnter',
--     --     config = function()
--     --         require('copilot').setup({
--     --             suggestion = {
--     --                 auto_trigger = true,
--     --                 keymap = {
--     --                     accept = '<C-l>',
--     --                     dismiss = '<C-o>',
--     --                     next = '<C-j>',
--     --                     prev = '<C-k>',
--     --                 },
--     --             },
--     --             copilot_node_command = os.getenv('HOME') .. '/.local/share/mise/installs/node/20.8.1/bin/node'
--     --         })
--     --     end,
--     -- }
--
--     use {
--         'CopilotC-Nvim/CopilotChat.nvim',
--         branch = 'canary',
--         requires = {
--             'nvim-lua/plenary.nvim',
--             'zbirenbaum/copilot.lua',
--         },
--         config = function ()
--             require('CopilotChat').setup {
--             }
--         end
--     }
--
--     -- LSP support
--     use {
--         'neoclide/coc.nvim',
--         branch = 'release',
--         setup = function()
--             vim.g.coc_node_path = os.getenv('HOME') .. '/.local/share/mise/installs/node/20.8.1/bin/node'
--             vim.g.coc_filetype_map = {
--                 htmldjango = 'html',
--                 json5 = 'json',
--             }
--         end,
--     }
--     use {
--         'fannheyward/telescope-coc.nvim',
--         config = function()
--             require "telescope".load_extension("coc")
--         end,
--     }
--
--     -- Language
--     use {
--         'mattn/emmet-vim', setup = function()
--         vim.g.user_emmet_leader_key = '<C-x>'
--     end,
--     }
--
--     use {
--         'nvim-treesitter/nvim-treesitter',
--         config = function()
--             require 'nvim-treesitter.configs'.setup {
--                 highlight = {
--                     enable = true,
--                 },
--             }
--
--             local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
--             parser_config.blade = {
--                 install_info = {
--                     url = "https://github.com/EmranMR/tree-sitter-blade",
--                     files = {"src/parser.c"},
--                     branch = "main",
--                 },
--                 filetype = "blade"
--             }
--         end,
--     }
--
--     use 'jparise/vim-graphql'
--     use {
--         "IndianBoy42/tree-sitter-just",
--         config = function()
--             require('tree-sitter-just').setup {}
--         end,
--     }
--
--     -- Apps
--     -- use 'glidenote/memolist.vim', { 'on': ['MemoNew', 'MemoGrep', 'MemoList'] }
--     --use 'skanehira/denops-silicon.vim'
--
--     use "thinca/vim-quickrun"
--
--     -- Editing
--
--     use "tpope/vim-repeat"
--
--     --use {
--     --    'tani/dmacro.nvim',
--     --    config = function ()
--     --        require('dmacro').setup({
--     --            dmacro_key = '<C-t>'
--     --        })
--     --    end
--     --}
--
--     use {
--         'kylechui/nvim-surround',
--         tag = "*",
--         config = function()
--             require('nvim-surround').setup({})
--         end,
--     }
--
--     use {
--         'easymotion/vim-easymotion',
--         setup = function()
--             vim.g.EasyMotion_do_mapping = 0
--             vim.g.EasyMotion_smartcase = 1
--             vim.g.EasyMotion_startofline = 0
--             vim.g.EasyMotion_keys = ';hklyuiopnm,qwertasdgzxcvbjf'
--             vim.g.EasyMotion_enter_jump_first = 1
--             vim.g.EasyMotion_space_jump_first = 1
--             vim.g.EasyMotion_use_migemo = 0
--         end,
--     }
--
--     if packer_bootstrap then
--         require('packer').sync()
--     end
-- end)
--
-- -- Automatically source and re-compile packer whenever you save this init.lua
-- local packer_group = vim.api.nvim_create_augroup('Packer', { clear = true })
-- vim.api.nvim_create_autocmd('BufWritePost', {
--     command = 'source <afile> | PackerCompile',
--     group = packer_group,
--     pattern = { '$MYVIMRC', '*.lua' },
-- })
