[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "terraform"]

[env]
_.path = ["./node_modules/.bin", "~/.local/share/aquaproj-aqua/bin"]

[tools]
"npm:svgo" = "latest"
"npm:graphql-language-service-cli" = "3.5.0"
"npm:neovim" = "latest"
lua = "5.1"
"npm:vercel" = "latest"
"npm:@hubspot/cli" = "latest"
"npm:imageoptim-cli" = "latest"
"npm:@squoosh/cli" = "latest"
"npm:imagemin-cli" = "latest"
"npm:prettier" = "latest"
"npm:rtm-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@playwright/mcp" = "latest"
"cargo:https://github.com/KOBA789/human-in-the-loop" = "rev:6f95553"
"npm:@google/gemini-cli" = "latest"
"npm:difit" = "latest"
"npm:ccusage" = "latest"
"npm:@sasazame/ccresume" = "latest"
node = "22"
ruby = "3.4.5"
"gem:lolcommits" = "latest"
python = "3"
"npm:vibetunnel" = "1.0.0-beta.15.2"
"npm:eas-cli" = "latest"

[settings.pipx]
uvx = true
