#!/bin/env bash

case $EUID in
    0) : already root - fall through ;;
    *) # not root, become root for the rest of this session
       # (and ask for the sudo password only once)
       exec sudo $0 "$@" ;;
esac

set -ex

echo "addn-hosts=/var/lib/hostsblock/hosts.block" > /etc/NetworkManager/dnsmasq.d/hostsblock.conf
pkill -HUP NetworkManager
